google_maps:
  browser_key: AIzaSyDVK21ipXemMEdvJohRr_XXyrvMtsHhCwc

# when TRUE rejects imperfect XML files
enable_strict_vipplus_parsing: true

map_color:
  colors:
    republican:     '#dc1521'
    democrat:       '#023582'
    other:          '#998675'

    nonpartisan1:   '#67aee8'
    nonpartisan2:   '#e5a433'

    referenda_yes:  '#7fc7b2'
    referenda_no:   '#1b4764'

    not_voting:     '#cccccc'
    not_reporting:  '#ffffff'
    tie:            '#EFDFBB'

    overvotes:      '#FF0000'
    undervotes:     '#00FF00'
    writeins:       '#0000FF'

  threshold:
    lower:  10
    upper:  20

  saturation:
    high:   0.7
    middle: 0.5
    low:    0.3

# Ordering of candidates in lists: 'vote_order', 'sort_order'
candidate_ordering: vote_order

ttv_logo_url: http://votestream.trustthevote.org

admin:
  user: enrsadmin
  pass: enrs23operations$2

development:
  enable_strict_vipplus_parsing: false

test:
  enable_strict_vipplus_parsing: false
