google_maps:
  browser_key: AIzaSyDVK21ipXemMEdvJohRr_XXyrvMtsHhCwc

# when TRUE rejects imperfect XML files
enable_strict_vipplus_parsing: true

party_colors:
  republican: "#ec012e"
  democrat:   "#123d74"

map_color_threshold:
  lower: 10
  upper: 20

# Ordering of candidates in lists: 'vote_order', 'sort_order'
candidate_ordering: vote_order

admin:
  user: enrsadmin
  pass: enrs23operations$2

development:
  enable_strict_vipplus_parsing: false

test:
  enable_strict_vipplus_parsing: false
