google_maps:
  browser_key: AIzaSyDVK21ipXemMEdvJohRr_XXyrvMtsHhCwc

# when TRUE rejects imperfect XML files
enable_strict_vipplus_parsing: true

map_color:
  colors:
    republican:     '#dc1521'
    democrat:       '#023582'
    male:     '#ffff00'
    female:       '#ff9900'
    other:          '#998675'
    other1:         '#00aa00'
    other2:         '#ddbb00'
    other3:         '#aa00aa'

    nonpartisan1:   '#67aee8'
    nonpartisan2:   '#e5a433'

    referenda_yes:  '#7fc7b2'
    referenda_no:   '#1b4764'

    not_voting:     '#cccccc'
    not_reporting:  '#ffffff'
    tie:            '#EFDFBB'

    overvotes:      '#888888'
    undervotes:     '#666666'
    writeins:       '#444444'

    participation:  '#daa520'

  threshold:
    lower:  10
    upper:  20
    
  gender_threshold:
    lower:  1
    upper: 2

  saturation:
    high:   0.7
    middle: 0.5
    low:    0.3

# Ordering of candidates in lists: 'vote_order', 'sort_order'
candidate_ordering: vote_order

ttv_logo_url: http://votestream.trustthevote.org

admin:
  user: enrsadmin
  pass: enrs23operations$2

development:
  enable_strict_vipplus_parsing: false

test:
  enable_strict_vipplus_parsing: false
