development:
  adapter:  mysql2
  host:     localhost
  database: enrs_d
  pool: 25
  username: enrs
  password: enrs

test:
  adapter:  mysql2
  host:     localhost
  database: enrs_t
  pool: 25
  username: enrs
  password: enrs
