development:
  adapter:  postgresql
  host:     localhost
  encoding: unicode
  database: enrs_d
  pool: 5
  username: enrs
  password: enrs

test:
  adapter:  postgresql
  host:     localhost
  encoding: unicode
  database: enrs_t
  pool: 5
  username: enrs
  password: enrs
