development:
  adapter: postgresql
  encoding: unicode
  database: enrs_d
  pool: 5
  username: enrs
  password: enrs

test:
  adapter: postgresql
  encoding: unicode
  database: enrs_t
  pool: 5
  username: enrs
  password: enrs

production:
  adapter: postgresql
  encoding: unicode
  database: enrs
  pool: 5
  username: enrs
  password:
